title: Vivek Devulapalli
description: Postdoctoral Researcher at EMPA
theme: minima

# Navigation
header_pages:
  - index.md
  - education.md
  - publications.md
  - contact.md

# Social links
github_username:  vivekdevulapalli07
linkedin_username: vivek-devulapalli-stem
google_scholar: TE3lrxoAAAAJ

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima theme settings
minima:
  date_format: "%b %-d, %Y"

# Social links (optional)
minima:
  social_links:
    - platform: github
      user_url: "https://github.com/vivekdevulapalli07"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/vivek-devulapalli-stem/"
    - platform: google_scholar
      user_url: "https://scholar.google.com/citations?user=TE3lrxoAAAAJ&hl=en"